apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d  
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config


argocd app create guestbook --repo https://github.com/dhruv160410116084/google-cloud-kubernetes-3-tier-app.git --path guestbook --dest-server https://kubernetes.default.svc --dest-namespace default